### ISSUE TITLE
Plans to put this on MELPA?

### ISSUE THREAD

**Issue by minad** [LuigiPiucco/yasnippet-capf#1]
Hi,

are there plans to publish this package on ELPA/MELPA? It seems that such a Capf has been reimplemented multiple times. Publishing it on a package archive would help avoiding duplicate work. See also:

* @justinbarclay's https://github.com/justinbarclay/yasnippet-capf
* @elken's https://github.com/elken/cape-yasnippet

**Comment by elken** [comment]
I was going to push both of my capfs (that and https://github.com/elken/cape-use-package) at some point, if you wouldn't mind reviewing them :) 

Mine was left intentionally empty while I tested it, but it seems good enough now.

**Comment by minad** [comment]
Hi @elken,

thanks, that's good! These packages are certainly useful for a wide user base. For Tempel there is no need to write an additional package since Tempel already comes with two Capfs (tempel-expand and tempel-complete). I wonder, how do you use Tempel? You probably invoke the commands manually instead of registering them as Capfs? 

My only criticism regarding your packages is that you use Cape and its private functions. Cape is not meant as a stable library, but rather as a set of user-level Capfs/commands and as a toolkit to tweak Capfs (the Capf transformers) on the level of the user configuration. In Cape I implemented and use a few trivial combinators for convenience, but Cape also provides a multitude of Capfs such that this is beneficial. Also Cape is or was my testing ground for Capfs, e.g., when I experimented with asynchronicity.

I suggest that you just inline or copy over some of the Cape functions to your packages. At first this may sound like a bad advice or malpractice, but I am sure you won't end up with much more code. See for example my Tempel package which intentionally also doesn't take advantage of Cape, but just follows the style and patterns of Cape.

I think it is better to have a bunch of \*-capf packages on the ELPAs than opening up another cape-\* ecosystem. If one looks at the innards it should be clear that Cape is generic, but to an outsider it will still look like a parallel word, similar to company-\*. 

What do you think?

**Comment by elken** [comment]
>  For Tempel there is no need to write an additional package since Tempel already comes with two Capfs (tempel-expand and tempel-complete). I wonder, how do you use Tempel? You probably invoke the commands manually instead of registering them as Capfs?

Yes I realized this after I sent the message, I was using `temepl-expand` rather than `tempel-complete` and they now show up and complete just fine, no package needed :)

As for the rest, yeah that does make sense. `cape` is a great library but not needed for "live" code. I'll probably go with initiating `capf-*` naming, to make it easier to see them in `package-menu` for those that use it :smile: 

I might action this today, depends how fast the rest of today vanishes...

**Comment by minad** [comment]
> Yes I realized this after I sent the message, I was using temepl-expand rather than tempel-complete and they now show up and complete just fine, no package needed :)

`tempel-expand` is also a Capf, but quite a restricted one. It only matches if you enter the *exact* template name in order to stay out of the way.

> As for the rest, yeah that does make sense. cape is a great library but not needed for "live" code. I'll probably go with initiating capf-* naming, to make it easier to see them in package-menu for those that use it.

Sounds good! I suggest to use `*-capf` to follow the naming of [existing packages](https://melpa.org/#/?q=capf) and also of the functions itself. These functions are usually called `*-completion-at-point`, e.g., `elisp-completion-at-point`.

EDIT: I see your point about better visibility in the package menu, but using a uniform naming convention seems more appropriate. Also Orderless ftw, it shouldn't matter where something appears in a string. ;)

**Comment by elken** [comment]
Ah, it seems a standard has already been formalized. No trouble :smile: 

> Also Orderless ftw, it shouldn't matter where something appears in a string. ;)

Agreed and while I think it should probably be part of core Emacs by now, sadly it's not and some people still have to deal with the long ns names :wink:

**Comment by minad** [comment]
> Agreed and while I think it should probably be part of core Emacs by now, sadly it's not and some people still have to deal with the long ns names

One can use `substring` if one wants to stick to Emacs core. :) Tbh I am very much against adding more stuff to core. I advocate for a leaner core, a leaner C runtime and moving packages from core to ELPA. There have certainly been a few good additions, but in the long term one will end up with cruft which will never get removed.

**Comment by justinbarclay** [comment]
I'd be so happy if @elken or @LuigiPiucco could merge their works to melpa. I've only had enough time to do a proof-of-concept and not formalize it into a package.

**Comment by elken** [comment]
https://github.com/melpa/melpa/pull/8671 is up as we speak :smile: Thanks Justin

**Comment by LuigiPiucco** [comment]
Sorry for the delay, I thought there wasn't that much interest in this for publishing right now, but seems I was wrong.

I think since @elken has already opened a PR, we can standardize on his repo. I ask then, are there any bits you find interesting here? Feel free to take anything. On a quick inspection, I can see the following as of potential interest:

- In the `:exit-function`, just calling `yas-expand` works, there's no need to delete backward and lookup the template again, since Yasnippet already does that anyway. It looks at what's before point, which we know will be the completed key/name.
- Implementing expansion preview in the doc buffer.
- Using the wrapper `completion-table-dynamic` may simplify things, it does caching and filtering for you, given an initial table with all possible candidates.
- For the key lookup, there's `yas-active-keys`, which could replace the manual lookup.

I can also PR these suggestions for you if you think any of them are valid.

**Comment by elken** [comment]
1 & 2 seem fine, 3 doesn't look like it does anything different to what's already there, 4 again because it supports name lookup and key lookup I'm not sure it does anything different but if you can add it in and make it work still then fine :smile:

**Comment by LuigiPiucco** [comment]
3 & 4 really don't do anything different, it's more to shorten the code a bit, reusing existing functionality. I'll PR them separately later then, pick what you find appropriate.

**Comment by minad** [comment]
See https://github.com/elken/yasnippet-capf/issues/11
